# Generated by Django 2.0.4 on 2018-05-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiverinfo',
            name='deliveryOrder',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='orderLines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderLines', to='order_api.OrderLines'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='receiverInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiverInfo', to='order_api.ReceiverInfo'),
        ),
    ]
