# Generated by Django 2.0.4 on 2018-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0002_auto_20180524_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='distributorNumber',
            field=models.CharField(blank=True, help_text='12343213', max_length=100, null=True, verbose_name='分销商编号'),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='itemCode',
            field=models.CharField(max_length=255, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='itemName',
            field=models.CharField(max_length=255, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='receiverinfo',
            name='area',
            field=models.CharField(max_length=255, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='receiverinfo',
            name='city',
            field=models.CharField(max_length=255, verbose_name='地址城市'),
        ),
        migrations.AlterField(
            model_name='receiverinfo',
            name='detailAddress',
            field=models.CharField(max_length=255, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='receiverinfo',
            name='mobile',
            field=models.CharField(max_length=255, verbose_name='收货人手机号'),
        ),
        migrations.AlterField(
            model_name='receiverinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='收货人姓名'),
        ),
        migrations.AlterField(
            model_name='receiverinfo',
            name='province',
            field=models.CharField(max_length=255, verbose_name='地址省份'),
        ),
    ]
