# Generated by Django 2.0.4 on 2018-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0003_auto_20180524_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='orderLines',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='orderLines',
            field=models.ManyToManyField(blank=True, null=True, to='order_api.OrderLines'),
        ),
    ]
